import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import vm from 'node:vm';

test('ships achievement and calendar UI with valid inline JavaScript', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'public', 'index.html'), 'utf8');
    assert.match(html, /id="badgeGrid"/);
    assert.match(html, /id="calendarGrid"/);
    assert.match(html, /id="analysisBars"/);
    assert.match(html, /id="generateCommentary"/);
    assert.match(html, /id="returnToWhatsApp"/);
    assert.match(html, /id="practiceNote"/);
    assert.doesNotMatch(html, /id="reflection"|id="bodyFeeling"/);
    assert.match(html, /splitLegacyNote\(practiceNote\)/);
    assert.match(html, /practiceNote,reflectionNote,bodyFeelingNote/);
    assert.match(html, /mergeLegacyNotes\(today\.reflectionNote,today\.bodyFeelingNote\)/);
    assert.doesNotMatch(html, /Promise\.all\(\[[^\]]*analysis\/commentary/);
    assert.match(html, /analysisRequestId/);
    assert.match(html, /commentaryRequestId/);
    assert.match(html, /target\.classList\.remove\('error','success'\)/);
    assert.match(html, /window\.close\(\);returnFallbackTimer=setTimeout/);
    assert.match(html, /window\.location\.replace\('\/whatsapp\/webapp\/return'\)/);
    assert.match(html, /},1500\)/);
    assert.match(html, /Promise\.allSettled\(\[loadProgress\(\),loadCalendar\(\)\]\)/);
    assert.match(html, /returnGeneration/);
    assert.match(html, /clearTimeout\(returnFallbackTimer\)/);
    const checkinRequest = html.indexOf("await api('/checkin'");
    const scheduleReturn = html.indexOf('scheduleWhatsAppReturn();', checkinRequest);
    const checkinError = html.indexOf('}catch(error)', scheduleReturn);
    assert.ok(checkinRequest >= 0 && scheduleReturn > checkinRequest && checkinError > scheduleReturn);
    const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
    assert.equal(scripts.length, 1);
    assert.doesNotThrow(() => new vm.Script(scripts[0][1]));
});
